version: '0.1'

#켬퓨터들
services:
    # mongo
    lait-database-mongo:
        image: mongo:5
        ports:
            - 27017:27017

    # mysql
    lait-database-mysql:
        image: mysql:8.0
        environment:
            MYSQL_DATABASE: 'final-docker'
            MYSQL_ROOT_PASSWORD: '@gywls4646'
        ports:
            - 3306:3306

    # nginx
    lait-backend-nginx:
        build:
            context: .
            dockerfile: Dockerfile.nginx
        ports:
            - 1935:1935
            - 8080:8080
        depends_on:
            - lait-backend-computer # lait-backend-computer 먼저 만들어진 후에 nginx 서버 생성

    # nest
    lait-backend-computer:
        depends_on:
            - lait-database-mongo
            - lait-database-mysql
        build:
            context: .
            dockerfile: Dockerfile.nest
        volumes:
            - ../la-it:/finalProject
        ports:
            - 3002:3002
        env_file:
            - ./.env.docker
