version: '3.7'

#켬퓨터들
services:
    # nginx
    lait-backend-nginx:
        build:
            context: .
            dockerfile: Dockerfile.nginx
        ports:
            - 1935:1935
            - 8080:8080
        depends_on:
            - lait-backend-computer # lait-backend-computer 먼저 만들어진 후에 nginx 서버 생성

    # nest
    lait-backend-computer:
        build:
            context: .
            dockerfile: Dockerfile.nest
        ports:
            - 3002:3002
        env_file:
            - ./.env.dev
